---
# Deploy Squid to existing VM (skip VM provisioning)
- name: Deploy Squid Forward Proxy to Existing VM
  hosts: proxy_servers
  gather_facts: no
  
  vars:
    ansible_ssh_pass: "changeme"
  
  roles:
    - squid_proxy

  post_tasks:
    - name: Display deployment summary
      debug:
        msg:
          - "✅ Squid proxy deployed to {{ ansible_host }}"
          - ""
          - "Test: curl -x {{ ansible_host }}:{{ squid_proxy_port }} -U {{ squid_proxy_user }}:{{ squid_proxy_pass }} http://ip.oxylabs.io/headers"

- name: Install CA on localhost
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  
  tasks:
    - name: Install CA certificate
      copy:
        src: files/squid-ca.crt
        dest: /usr/local/share/ca-certificates/squid-proxy.crt
        mode: '0644'
      register: ca_copied

    - name: Update certificates
      command: update-ca-certificates
      when: ca_copied.changed
